zig/prototype/urls.py
from django.conf.urls import url
from . import views
from django.contrib import admin


admin.autodiscover()

app_name = "prototype"
urlpatterns = [
    url(r'^bigdata/$', views.bigdata_trend_testing, name='bigdata'),
    url(r'^strategy/$', views.strat_trend_manage, name='strategy'),
    url(r'^strategymanage/$', views.strat_manage, name='strategy_manage'),
    url(r'^strategyshop/$', views.strat_shop, name='strategy_shop'),
    url(r'^bigdata_result/$', views.bigdata_trend_test_result, name='bigdata_result'),
    url(r'^bigdata_result_new/$', views.bigdata_trend_test_result_new, name='bigdata_result_new'),
    url(r'^bigdata_mktdata/$', views.bigdata_mktdata, name='bigdata_mktdata'),
    url(r'^zigadmin/$', views.zig_admin),
    url(r'^aboutus/$', views.about_us, name='aboutus'),
    url(r'^admin/', admin.site.urls),
    url(r'^login_test/', views.login_testing, name='login_test'),
    url(r'^api/$', views.api, name='api'),
    url(r'^$', views.strat_trend_manage),
    url(r'^.+/$', views.under_construction),
]

zig/zigweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from prototype.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # the original url mapping changed to prototype/urls.py
    url(r'', include('prototype.urls', namespace='zig-prototype'))
]

zig/prototype/models.py
# -*- coding: utf-8 -*-

from django.db import models
import json

# Add
#  s = Mysite(title='test_Title', url='http://testURL', author='guoqingc', num='0')
#  s.save()

# Search and Update
# s = Mysite.objects.get(title='test_Title')
# s.url = 'http://testURL2'
# s.save()

# Delete
# s = Mysite.objects.get(title='test_Title')
# s.delete()

# Delete All
# Mysite.objects.all().delete()


class Mysite(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()
    author = models.CharField(max_length=100)
    num = models.IntegerField()


class Indexs(models.Model):
    name = models.CharField(max_length=50)
    definition = models.CharField(max_length=100)


class RegressionTest(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        permissions = (
            ("run_test", "Run regression test"),
            ("view_test_result", "View regression test result")
        )


class ProductInfo(models.Model):
    symbol = models.CharField(max_length=10, primary_key=True)
    cn_name = models.CharField(max_length=20)
    issue_type = models.CharField(max_length=12)


class MyData:
    #currentPath = os.getcwd()
    #parentPath = os.path.split(currentPath)[0]
    #dataFilePath = os.path.join(currentPath, 'static/data/avg_5_10.json').replace('\\', '/')

    #dataFile = json.load(open(dataFilePath, 'r'))
    #avg_5_10 = dataFile['avg_5_10']

    buyindexes = ["五日上穿十日", "五日上穿二十日", "五日上穿三十日"]
    sellindexes = ["五日下穿十日", "五日下穿二十日", "五日下穿三十日"]
    # Date format mm dd, yy
    startDate = "1 1, 2013"
    endDate = "6 30, 2013"

    dateList = [
        "2013/1/24", "2013/1/25", "2013/1/28", "2013/1/29", "2013/1/30",
        "2013/1/31", "2013/2/1", "2013/2/4", "2013/2/5", "2013/2/6",
        "2013/2/7", "2013/2/8", "2013/2/18", "2013/2/19", "2013/2/20",
        "2013/2/21", "2013/2/22", "2013/2/25", "2013/2/26", "2013/2/27",
        "2013/2/28", "2013/3/1", "2013/3/4", "2013/3/5", "2013/3/6",
        "2013/3/7", "2013/3/8", "2013/3/11", "2013/3/12", "2013/3/13",
        "2013/3/14", "2013/3/15", "2013/3/18", "2013/3/19", "2013/3/20",
        "2013/3/21", "2013/3/22", "2013/3/25", "2013/3/26", "2013/3/27",
        "2013/3/28", "2013/3/29", "2013/4/1", "2013/4/2", "2013/4/3",
        "2013/4/8", "2013/4/9", "2013/4/10", "2013/4/11", "2013/4/12",
        "2013/4/15", "2013/4/16", "2013/4/17", "2013/4/18", "2013/4/19",
        "2013/4/22", "2013/4/23", "2013/4/24", "2013/4/25", "2013/4/26",
        "2013/5/2", "2013/5/3", "2013/5/6", "2013/5/7", "2013/5/8",
        "2013/5/9", "2013/5/10", "2013/5/13", "2013/5/14", "2013/5/15",
        "2013/5/16", "2013/5/17", "2013/5/20", "2013/5/21", "2013/5/22",
        "2013/5/23", "2013/5/24", "2013/5/27", "2013/5/28", "2013/5/29",
        "2013/5/30", "2013/5/31", "2013/6/3", "2013/6/4", "2013/6/5",
        "2013/6/6", "2013/6/7", "2013/6/13"
        ]
    marketData = [
                    [2320.26, 2302.6, 2287.3, 2362.94],
                    [2300, 2291.3, 2288.26, 2308.38],
                    [2295.35, 2346.5, 2295.35, 2346.92],
                    [2347.22, 2358.98, 2337.35, 2363.8],
                    [2360.75, 2382.48, 2347.89, 2383.76],
                    [2383.43, 2385.42, 2371.23, 2391.82],
                    [2377.41, 2419.02, 2369.57, 2421.15],
                    [2425.92, 2428.15, 2417.58, 2440.38],
                    [2411, 2433.13, 2403.3, 2437.42],
                    [2432.68, 2434.48, 2427.7, 2441.73],
                    [2430.69, 2418.53, 2394.22, 2433.89],
                    [2416.62, 2432.4, 2414.4, 2443.03],
                    [2441.91, 2421.56, 2415.43, 2444.8],
                    [2420.26, 2382.91, 2373.53, 2427.07],
                    [2383.49, 2397.18, 2370.61, 2397.94],
                    [2378.82, 2325.95, 2309.17, 2378.82],
                    [2322.94, 2314.16, 2308.76, 2330.88],
                    [2320.62, 2325.82, 2315.01, 2338.78],
                    [2313.74, 2293.34, 2289.89, 2340.71],
                    [2297.77, 2313.22, 2292.03, 2324.63],
                    [2322.32, 2365.59, 2308.92, 2366.16],
                    [2364.54, 2359.51, 2330.86, 2369.65],
                    [2332.08, 2273.4, 2259.25, 2333.54],
                    [2274.81, 2326.31, 2270.1, 2328.14],
                    [2333.61, 2347.18, 2321.6, 2351.44],
                    [2340.44, 2324.29, 2304.27, 2352.02],
                    [2326.42, 2318.61, 2314.59, 2333.67],
                    [2314.68, 2310.59, 2296.58, 2320.96],
                    [2309.16, 2286.6, 2264.83, 2333.29],
                    [2282.17, 2263.97, 2253.25, 2286.33],
                    [2255.77, 2270.28, 2253.31, 2276.22],
                    [2269.31, 2278.4, 2250, 2312.08],
                    [2267.29, 2240.02, 2239.21, 2276.05],
                    [2244.26, 2257.43, 2232.02, 2261.31],
                    [2257.74, 2317.37, 2257.42, 2317.86],
                    [2318.21, 2324.24, 2311.6, 2330.81],
                    [2321.4, 2328.28, 2314.97, 2332],
                    [2334.74, 2326.72, 2319.91, 2344.89],
                    [2318.58, 2297.67, 2281.12, 2319.99],
                    [2299.38, 2301.26, 2289, 2323.48],
                    [2273.55, 2236.3, 2232.91, 2273.55],
                    [2238.49, 2236.62, 2228.81, 2246.87],
                    [2229.46, 2234.4, 2227.31, 2243.95],
                    [2234.9, 2227.74, 2220.44, 2253.42],
                    [2232.69, 2225.29, 2217.25, 2241.34],
                    [2196.24, 2211.59, 2180.67, 2212.59],
                    [2215.47, 2225.77, 2215.47, 2234.73],
                    [2224.93, 2226.13, 2212.56, 2233.04],
                    [2236.98, 2219.55, 2217.26, 2242.48],
                    [2218.09, 2206.78, 2204.44, 2226.26],
                    [2199.91, 2181.94, 2177.39, 2204.99],
                    [2169.63, 2194.85, 2165.78, 2196.43],
                    [2195.03, 2193.8, 2178.47, 2197.51],
                    [2181.82, 2197.6, 2175.44, 2206.03],
                    [2201.12, 2244.64, 2200.58, 2250.11],
                    [2236.4, 2242.17, 2232.26, 2245.12],
                    [2242.62, 2184.54, 2182.81, 2242.62],
                    [2187.35, 2218.32, 2184.11, 2226.12],
                    [2213.19, 2199.31, 2191.85, 2224.63],
                    [2203.89, 2177.91, 2173.86, 2210.58],
                    [2170.78, 2174.12, 2161.14, 2179.65],
                    [2179.05, 2205.5, 2179.05, 2222.81],
                    [2212.5, 2231.17, 2212.5, 2236.07],
                    [2227.86, 2235.57, 2219.44, 2240.26],
                    [2242.39, 2246.3, 2235.42, 2255.21],
                    [2246.96, 2232.97, 2221.38, 2247.86],
                    [2228.82, 2246.83, 2225.81, 2247.67],
                    [2247.68, 2241.92, 2231.36, 2250.85],
                    [2238.9, 2217.01, 2205.87, 2239.93],
                    [2217.09, 2224.8, 2213.58, 2225.19],
                    [2221.34, 2251.81, 2210.77, 2252.87],
                    [2249.81, 2282.87, 2248.41, 2288.09],
                    [2286.33, 2299.99, 2281.9, 2309.39],
                    [2297.11, 2305.11, 2290.12, 2305.3],
                    [2303.75, 2302.4, 2292.43, 2314.18],
                    [2293.81, 2275.67, 2274.1, 2304.95],
                    [2281.45, 2288.53, 2270.25, 2292.59],
                    [2286.66, 2293.08, 2283.94, 2301.7],
                    [2293.4, 2321.32, 2281.47, 2322.1],
                    [2323.54, 2324.02, 2321.17, 2334.33],
                    [2316.25, 2317.75, 2310.49, 2325.72],
                    [2320.74, 2300.59, 2299.37, 2325.53],
                    [2300.21, 2299.25, 2294.11, 2313.43],
                    [2297.1, 2272.42, 2264.76, 2297.1],
                    [2270.71, 2270.93, 2260.87, 2276.86],
                    [2264.43, 2242.11, 2240.07, 2266.69],
                    [2242.26, 2210.9, 2205.07, 2250.63],
                    [2190.1, 2148.35, 2126.22, 2190.1]
                ]
    resultList = [
                    [
                        ["1 24, 2013", 13560434, 0.8], ["3 29, 2013", 7526158.5, 1.2], ["5 24, 2013", 8105835, 1.5], ["6 4, 2013", 7971452.5, 3]],
                    [
                        ["1 28, 2013", 13560434, 0.6], ["3 26, 2013", 7526158.5, 1.6], ["4 24, 2013", 8105835, 1.9], ["6 4, 2013", 7971452.5, 5]],
                ]
    dateList2 = [
        '2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04', '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08', '2015-01-09', '2015-01-10', '2015-01-11', '2015-01-12', '2015-01-13', '2015-01-14', '2015-01-15', '2015-01-16', '2015-01-17', '2015-01-18', '2015-01-19', '2015-01-20', '2015-01-21', '2015-01-22', '2015-01-23', '2015-01-24', '2015-01-25', '2015-01-26', '2015-01-27', '2015-01-28', '2015-01-29', '2015-01-30', '2015-02-01', '2015-02-02', '2015-02-03', '2015-02-04', '2015-02-05', '2015-02-06', '2015-02-07', '2015-02-08', '2015-02-09', '2015-02-10', '2015-02-11', '2015-02-12', '2015-02-13', '2015-02-14', '2015-02-15', '2015-02-16', '2015-02-17', '2015-02-18', '2015-02-19', '2015-02-20', '2015-02-21', '2015-02-22', '2015-02-23', '2015-02-24', '2015-02-25', '2015-02-26', '2015-02-27', '2015-02-28', '2015-03-01', '2015-03-02', '2015-03-03', '2015-03-04', '2015-03-05', '2015-03-06', '2015-03-07', '2015-03-08', '2015-03-09', '2015-03-10', '2015-03-11', '2015-03-12', '2015-03-13', '2015-03-14', '2015-03-15', '2015-03-16', '2015-03-17', '2015-03-18', '2015-03-19', '2015-03-20', '2015-03-21', '2015-03-22', '2015-03-23', '2015-03-24'
    ]

    marketData2 = [
        00, 30, 45, 23, 50, 34, 21, 5, -10, -30, -47, -65,-45, -50, 00, 60, 65, 60, 67, 80, 86, 50, 40, 65, 60, 40, 35, 23, 11, 15, 20, 15, 12, 20, 40, 30, 60, 78, 67, 65, 60, 22, 19, 20, 21, 20, 22, 23, 32, 45, 55, 60, 54, 56, 54, 64, 70, 87, 98, 70, 76, 87, 80, 70, 76, 87, 97, 90, 80, 78, 65, 65, 76, 46, 40, 55, 74, 89, 130, 120, 130, 135
    ]

    gain_5_50 = """
        [
            ['2010/5/21', 1, 1],

zig/prototype/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.shortcuts import render_to_response
from .controls import *
from .product import *
from Utility import webapi
from rtmd import *
from django.http import HttpResponse, HttpResponseRedirect


def login_testing(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/admin/login/?next=%s' % request.path)
    if not request.user.has_perm('prototype.view_test_result'):
        return HttpResponse("您没有运行回测的权限，请联系管理员。")
    return render_to_response('login_test.html')


def bigdata_trend_testing(request):
    return render_to_response("bigdata_trend_testing.html", get_context("bigdata_trend_testing"))


def bigdata_trend_test_result(request):
    return render_to_response('bigdata_trend_test_result.html', get_context("bigdata_trend_test_result"))


def bigdata_trend_test_result_new(request):
    return render_to_response('bigdata_trend_test_result_new.html', get_context("bigdata_trend_test_result"))


def bigdata_mktdata(request):
    return render_to_response('bigdata_mkt_data.html', get_context("bigdata_mkt_data"))


def strat_trend_manage(requst):
    return render_to_response("strat_manage_index.html", get_context("strat_manage_index"))


def strat_manage(requst):
    return render_to_response("strat_manage.html", get_context("strat_manage"))


def strat_shop(requst):
    return render_to_response("strat_shop.html", get_context("strat_shop"))


def zig_admin(request):
    message = "No action specified."
    if request.GET.get('refreshproduct') == 'true':
        message = ProductHelper.refresh_productDB(webapi)
    return render_to_response("zigadmin.html", {"message": message, "no_navBar": True})


def api(request):
    result = ""
    nocache = False

    if request.GET.get('ty') == 'rtmd':
        products = request.GET.get('value')
        if products is not None and len(products) > 0:
            result = SinaRTMD(webapi.getDetailedRtmd(products)).toJsonString()
            nocache = True
    response = HttpResponse(result)
    # set no cache in repsonse header
    if nocache:
        response['Cache-Control'] = 'no-cache'
    return response


def about_us(requst):
    return render_to_response("about_us.html", get_context("about_us"))


def under_construction(requst):
    return render_to_response("under_construction.html", get_context("under_construction"))

# Set active items in Title Bar and Nav Bar
def get_context(pageName):
    context_mapping = {
        "bigdata_trend_testing":
            {
                "title_bigdata": "active",
                "nav_trendTest": "active",
                "buy_indexes_list": SelectDropdown("buyList", "multiselect", MyData.buyindexes),
                "sell_indexes_list": SelectDropdown("sellList", "multiselect", MyData.sellindexes),
            },
        "bigdata_trend_test_result":
            {
                "title_bigdata": "active",
                "nav_historyTest": "active",
                "testResults": MyData.testResults,
            },
        "bigdata_mkt_data":
            {
                "title_bigdata": "active",
                "nav_mktData": "active",
            },
        "strat_manage":
            {
                "title_strategy": "active",
                "nav_strategy_mge": "active",
                "buy_indexes_list": SelectDropdown("buyList", "multiselect", MyData.buyindexes),
                "sell_indexes_list": SelectDropdown("sellList", "multiselect", MyData.sellindexes),
            },
        "strat_manage_index":
            {
                "title_strategy": "active",
                "nav_index_manage": "active",
            },
        "strat_shop":
            {
                "title_strategy": "active",
                "nav_strat_shop": "active",
            },
        "about_us":
            {
                "title_aboutUs": "active",
                "no_navBar": True,
            },
        "under_construction":
            {
                "no_navBar": True,
            }
    }
    return context_mapping[pageName]

zig/prototype/templates/about_us.html
{% extends "base.html" %}

{%  block no_navBarContent %}
                        <div class="container center-block" style="width: 70%" >
        <div class="row">
<br/><br/>
    <div class="panel panel-default ">
        <div class="panel-body ">
                <div class="page-header-top">

            <h1>关于我们 <small>find out more about us</small></h1>

    </div>
            <p>
                至构金融成立于2015年。核心成员来自国际各知名投行，创始成员覆盖金融、数学、投资管理和市场营销领域。
                至构金融致力于打造专业的量化策略交易平台，以华尔街国际投行所采用的金融大数据分析系统为核心，建立国际级的程序化交易系统和严格的风控系统，为国内不断兴起的财富管理机构和大众富裕人群提供金融技术服务。
            </p>
            联系我们: contactus@zigstrat.com
        </div>
    </div>

            </div>
</div>
{% endblock %}

zig/prototype/templates/bigdata_base.html
{% extends "base.html" %}

{%  block navBar %}
    <div class="list-group" >
        <a href="{% url 'prototype:bigdata' %}" class="list-group-item {{ nav_trendTest }}">趋势指标回测</a>
        <a href="{% url 'prototype:bigdata_result' %}" class="list-group-item {{ nav_historyTest }}">回测结果</a>
{#        <a href="{% url 'prototype:bigdata_history' %}" class="list-group-item {{ nav_historyData }}">历史数据查询</a>#}
        <a href="{% url 'prototype:bigdata_mktdata' %}" class="list-group-item {{ nav_mktData }}">市场数据</a>
    </div>
{% endblock %}

zig/prototype/templates/bigdata_mkt_data.html
{% extends "bigdata_base.html" %}
{% load staticfiles %}


{% block content %}
    <script src="{% static "js/Utils.js" %}"></script>
    <script src="{% static "js/select2.full.min.js" %}"></script>
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}" type="text/css"/>

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="page-header">
                <h1>大数据
                    <small>市场数据<small>(demo版30秒实时数据刷新间隔)</small></small>
                </h1>
            </div>
            选择股票
            <select multiple="multiple" id="stockSelector2" style="width: 60%">
                <option value="sz300498" py="wsgf">温氏股份</option>
                <option value="sz300497" py="fxgf">富祥股份</option>
                <option value="sz300496" py="zkcd">中科创达</option>
                <option value="sz300495" py="msst">美尚生态</option>
                <option value="sz300494" py="stwl">盛天网络</option>
                <option value="sz300493" py="rxkj">润欣科技</option>
                <option value="sz300492" py="sdsj">山鼎设计</option>
                <option value="sh600080" py="jhgf">金花股份</option>
                <option value="sh600079" py="rfyy">人福医药</option>
                <option value="sh600078" py="cxgf">澄星股份</option>
                <option value="sh600077" py="sdgf">宋都股份</option>
                <option value="sh600076" py="qnhg">青鸟华光</option>
            </select>
            选择数据类型
            <select class="multiselect">
                <option selected="selected">实时数据</option>
                {#                <option >逐笔成交数据</option>#}
                {#                <option >分钟数据</option>#}
                {#                <option >小时数据</option>#}
                {#                <option >日数据</option>#}
            </select>
            {#            选择时间范围#}

            <div id="dataContainer">

            </div>

        </div>
    </div>

    <script>
        var select2;
        $(document).ready(function () {
            $('.multiselect').multiselect();

            $.fn.select2.amd.require(['select2/compat/matcher'], initSelect2);

            $("#stockSelector2").on("change", function (e) {
                refreshMktData();
            });
        });

        initSelect2 = function (oldMatcher) {
            $("#stockSelector2").select2({
                        matcher: productMatcher,
                        minimumInputLength: 3,
                        placeholder: "请输入股票名称/代码/拼音， '***'显示全部"
                    }
            );
        };

        function productMatcher(params, data) {
            matchArray = [data.text.toLowerCase(), data.id.toLowerCase(), data.element.getAttribute("py").toLowerCase()];
            //var matchArray = [data.text.toLowerCase(), data.id.toLowerCase()];
            var input = params.term.toLowerCase();
            if(input.indexOf("***") > -1)
                return data;
            for (var i = 0; i < matchArray.length; i++) {
                if (matchArray[i].indexOf(input) > -1)
                    return data;
            }
            return null;
        }

        var timer = null;
        function startTimer() {
            if (timer != null)
                clearTimeout(timer);
            timer = setTimeout("refreshMktData()", 30000);
        }

        function refreshMktData() {
            var selectedItems = $("#stockSelector2").select2("data");
            var products = "";
            for (var i = 0; i < selectedItems.length; i++) {
                products += selectedItems[i].id + ","
            }
            if (products != "") {
                getMktData(products);
                startTimer();
            }
            else {
                //clear table
                createTable(null, "dataContainer");
            }
        }

        function getMktData(products) {
            $.getJSON("{% url 'prototype:api'%}?ty=rtmd&value=" + products, processMktData);
        }

        function processMktData(json) {
            createTable(json, "dataContainer", "table table-striped", true, ["cn_name", "ap", "bp", "vs", "cp", "symbol", "op", "time"]);
        }
    </script>
{% endblock %}

zig/prototype/templates/bigdata_trend_test_result_new.html
{% extends "bigdata_base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="page-header">
                <h1>量化<small>趋势指标回测结果</small></h1>
            </div>

            <div>股票名称:            测试股票1</div>
            <div class="col-md-12" id="container"></div>

            <!-- import highChart -->
            <script type="text/javascript" src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
            <script src="{% static 'js/highstock/js/highstock.js' %}"></script>
            <script src="{% static 'js/resultCharts.js' %}" ></script>

            <script type="text/javascript">
                Highcharts.setOptions(resultOptions);
                var testResults = {{ testResults|safe }};
                $(document).ready(function(){
                    renderResults();
                });

                function renderResults(){
                    var resultIndex = 0;
                    testResults.forEach(function(result){
                        addResult(result, "test" + resultIndex.toString());
                        resultIndex ++;
                    });
                }

                function addResult(result, resultID){
                    var container = document.getElementById("container");
                    var resultContainer = document.createElement("div");
                    resultContainer.id = resultID + "container";
                    resultContainer.textContent = result["testName"];
                    container.appendChild(resultContainer);

                    for (dataKey in result["testResult"]){
                        renderChart(resultContainer, resultID + dataKey,  result["testResult"][dataKey]);
                    };
                }

                function  renderChart(parentContainer, dataID, data){
                    var dataContainer = document.createElement("div");
                    var dataChart = document.createElement("div");
                    dataContainer.textContent = data["name"];
                    dataContainer.id = dataID + "container";
                    dataChart.id = dataID;
                    dataContainer.appendChild(dataChart);
                    parentContainer.appendChild(dataContainer);

                    // parse x axes data
                    var dateArray = formatDate(data["dateList"]);
                    // set option
                    var option = new Object();
                    option.chart = resultOptions.chart;
                    option.chart.renderTo = dataID;
                    option.legend = resultOptions.legend;
                    option.series = resultOptions.series;
                    var seriesIndex = 0;
                    for (dataKey in data) {
                        if(dataKey != "name" & dataKey != "dateList"){
                            if (!option.series[seriesIndex]) {
                                option.series[seriesIndex] = new Object();
                            }
                            option.series[seriesIndex].name = dataKey;
                            option.series[seriesIndex].showInLegend = true;
                            option.series[seriesIndex].data = formatResultData(dateArray, data[dataKey]);
                            seriesIndex ++;
                        }
                    }
                    // create chart
                    var chart = new Highcharts.StockChart(option);
                }
                function formatDate(dateList){
                    var dateArray = [];
                    dateList.forEach(function (dateItem) {
                        var dateSet = dateItem.split('/');
                        dateArray.push(Date.parse(dateSet[1]+"/"+dateSet[2]+"/"+dateSet[0]));
                    });
                    return dateArray;
                }

                function formatResultData(dateArray, dataSet){
                    var resultData = [];
                    for(var i = 0; i < dateArray.length; i++){
                        resultData.push([dateArray[i], dataSet[i]]);
                    }
                    return resultData;
                }
            </script>
        </div>
    </div>
{% endblock %}

zig/prototype/templates/strat_base.html
{% extends "base.html" %}


{%  block navBar %}
    <div class="list-group" >
{#        <a href="#" class="list-group-item {{ nav_running_strategy_mge }}">投资策略运行</a>#}
        <a href="{% url 'prototype:strategy' %}" class="list-group-item {{ nav_index_manage }}">指标管理</a>
        <a href="{% url 'prototype:strategy_manage' %}" class="list-group-item {{ nav_strategy_mge }}">策略管理</a>
{#        <a href="mannualorder" class="list-group-item">手动下单撤单</a>#}
{#        <a href="basket" class="list-group-item {{ nav_stock_basket }}">股票池管理</a>#}
        <a href="{% url 'prototype:strategy_shop' %}" class="list-group-item {{ nav_strat_shop }}">策略商店</a>
    </div>
{% endblock %}

zig/prototype/templates/under_construction.html
{% extends "base.html" %}
{% load staticfiles %}

{%  block no_navBarContent %}
    <div class="container center-block" style="width: 70%" >
        <div class="row">
            <br/><br/>
            <div class="panel panel-default ">
                <div class="panel-body ">
                    <div class="page-header-top">

                        <h1>网站建设中 <small>under construction</small></h1>

                    </div>
                    <img src="{% static 'img/under_construction.png' %}" />
                    <p>
                        至构金融成立于2015年。核心成员来自国际各知名投行，创始成员覆盖金融、数学、投资管理和市场营销领域。
                        至构金融致力于打造专业的量化策略交易平台，以华尔街国际投行所采用的金融大数据分析系统为核心，建立国际级的程序化交易系统和严格的风控系统，为国内不断兴起的财富管理机构和大众富裕人群提供金融技术服务。
                    </p>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

zig/prototype/templates/zigBigdataBase.html
{% extends "zigBase.html" %}


{%  block navBar %}
{#<br/>#}
{#    <br/>#}
    <div class="list-group" >
        <a href="#" class="list-group-item {{ nav_trendTest }}">趋势指标回测</a>
        <a href="#" class="list-group-item {{ nav_historyData }}">历史数据查询</a>
        <a href="#" class="list-group-item {{ nav_historyTest }}">历史回测</a>
    </div>
{% endblock %}

zig/prototype/templates/zigadmin.html
{% extends "base.html" %}
{% load staticfiles %}

{%  block no_navBarContent %}
    <div class="container center-block" style="width: 70%" >
        <div class="row">
            <br/><br/>
            <div class="panel panel-default ">
                <div class="panel-body ">
                    <div class="page-header-top">
                        <h1>Admin</h1>
                        {{ message }}
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}